[project]
name = "restore-all"
version = "0.1.0"
description = "Aplicación de consola para restuarar base de datos en SQL Server indicando una carpeta con un listado de archivos de backup"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.3",
    "colorama>=0.4.6",
    "docker>=7.1.0",
    "dotenv>=0.9.9",
    "pydantic>=2.13.3",
]
